#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /etc/runit/functions

[ -r /etc/runit/rc.conf ] && . /etc/runit/rc.conf

msg "Welcome to Artix Linux!"

if [ -x /usr/bin/openrc ] && [ "$SVMANAGER" = "openrc" ]; then
  # Start core services: we'll use OpenRC for this.
  msg "Initializing runlevel sysinit with OpenRC..."
  openrc sysinit || msg_error "Failed to start sysinit runlevel"
else
  # Start core services: one-time system tasks.
  detect_virt
  for f in /etc/runit/core-services/*.sh; do
      [ -r $f ] && . $f
  done
fi

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
	chmod 0600 /var/log/dmesg.log
else
	chmod 0644 /var/log/dmesg.log
fi

mkdir -p /run/runit
install -m100 /dev/null /run/runit/stopit

msg "Initialization complete, running stage 2..."
