#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /etc/runit/functions

load_conf '/etc/runit/rc.conf'

msg "Welcome to Artix Linux!"

if [ -x /usr/bin/openrc ] && [ "$SVMANAGER" = "openrc" ]; then
    # Start sysinit services: we'll use OpenRC for this.
    msg "Initializing runlevel sysinit with OpenRC..."
    openrc sysinit || msg_error "Failed to start sysinit runlevel"
else
    # Start sysinit services: one-time system tasks.
    detect_virt
    for f in /etc/runit/sysinit-services/*.sh; do
        case $f in
            *lvm.sh|*dmraid.sh|*btrfs.sh|*cryptsetup.sh)
                if ${USE_LVM}; then
                    [ -r $f ] && . $f
                fi
                if ${USE_DMRAID}; then
                    [ -r $f ] && . $f
                fi
                if ${USE_BTRFS}; then
                    [ -r $f ] && . $f
                fi
                if ${USE_CRYPT}; then
                    [ -r $f ] && . $f
                fi
                if ${USE_SWAP}; then
                    [ -r $f ] && . $f
                fi
                if ${USE_ZFS}; then
                    [ -r $f ] && . $f
                fi
            ;;
            *) [ -r $f ] && . $f ;;
        esac
    done
fi

dmesg >/var/log/dmesg.log
if [ $(sysctl -n kernel.dmesg_restrict 2>/dev/null) -eq 1 ]; then
    chmod 0600 /var/log/dmesg.log
else
    chmod 0644 /var/log/dmesg.log
fi

mkdir -p /run/runit
install -m100 /dev/null /run/runit/stopit

msg "Initialization complete, running stage 2..."
