#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /etc/runit/functions
detect_virt
[ -r /etc/runit/rc.conf ] && . /etc/runit/rc.conf

if [ -e /run/runit/reboot ]; then
    chmod 100 /run/runit/reboot
fi

[ -x /etc/runit/rc.shutdown ] && /etc/runit/rc.shutdown

for f in /etc/runit/shutdown-services/*.sh; do
    [ -r $f ] && . $f
done

msg "Stage 3 completed."
