#!/bin/sh
# vim: set ts=4 sw=4 et:

PATH=/usr/bin:/usr/sbin

. /etc/runit/functions
detect_virt
[ -r /etc/runit/rc.conf ] && . /etc/runit/rc.conf

if [ -e /run/runit/reboot ]; then
    chmod 100 /run/runit/reboot
fi

[ -x /etc/runit/rc.shutdown ] && /etc/runit/rc.shutdown

for f in /etc/runit/shutdown-services/*.sh; do
    [ -r $f ] && . $f
done

sync

if [ -z "$VIRTUALIZATION" ]; then
    deactivate_vgs
    deactivate_crypt
    if [ -e /run/runit/reboot ] && command -v kexec >/dev/null; then
        msg "Triggering kexec..."
        kexec -e 2>/dev/null
        # not reached when kexec was successful.
    fi
fi
